"""created relationships of books

Revision ID: d0c893c96cab
Revises: a3c982881a2e
Create Date: 2026-08-25 02:39:52.620852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0c893c96cab'
down_revision: Union[str, Sequence[str], None] = 'a3c982881a2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('books', sa.Column('author_id', sa.Integer(), nullable=True))
    # op.add_column('books', sa.Column('category_id', sa.Integer(), nullable=True))
    # with op.batch_alter_table("books") as batch_op:
    #     batch_op.create_foreign_key(
    #         "fk_books_author",
    #         "authors",
    #         ['author_id'], 
    #         ['id']
    #     )
    #     batch_op.create_foreign_key(
    #         "fk_books_category",
    #         "categories",
    #         ['category_id'], 
    #         ['id']
    #     )
    # op.drop_column('books', 'author')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('books', sa.Column('author', sa.VARCHAR(), nullable=True))
    # op.drop_constraint(None, 'books', type_='foreignkey')
    # op.drop_constraint(None, 'books', type_='foreignkey')
    # op.drop_column('books', 'category_id')
    # op.drop_column('books', 'author_id')
    # ### end Alembic commands ###
